version: '3.8'

services:
  sprite-generator:
    build: .
    container_name: image-generation-api
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - ./logs:/app/logs
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    networks:
      - sprite-generator-network

networks:
  sprite-generator-network:
    driver: bridge

volumes:
  logs:
    driver: local
