version: '3.8'

services:
  image-api:
    build: .
    container_name: image-generation-api
    ports:
      - "8000:8000"
    environment:
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - image-api-network

networks:
  image-api-network:
    driver: bridge

volumes:
  logs:
    driver: local
